from flask import Flask, g
from peewee import PostgresqlDatabase


app = Flask(__name__)
app.config.from_object('config.Configuration')

db = PostgresqlDatabase(app.config['DATABASE_NAME'])


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()

def before_request():
    g.db = db
    g.db.connect()

def after_request(response):
    g.db.close()
    return response
